buildSrc/src/main/kotlin/FernflowerTask.kt
runescape-client/src/main/java/Client.java
runescape-client/src/main/java/Scene.java

PR to update some mismatched intValues

Updating values according to deob

---

runelite-client/src/main/scripts/XpDropChanged.rs2asm

This is an addition to commit: 96527bc0707c0a84ac07687278f80bcc07eff973

client: fix cs2

---

runelite-client/src/main/resources/transports.json

fixed some transport agility requirements near zeah mine

Fix some transport requirements

---

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java

Better varbit change check, improved performance.
Instead of iterating over every varbit id it now only iterates over the varbit ids linked to the varp index to compare old -> new values.

mixins: fix varbit changed event

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

Updates direct packet API for new rev.
Added continue object packet to Widget Packets API.

Probably fixes direct packet api and added a widget packet

---

runelite-mixins/src/main/java/net/runelite/mixins/RSKeyHandlerMixin.java

Fix java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 128

mixins: (KeyHandler) fix key events

---

runelite-client/src/main/java/net/unethicalite/api/magic/RunePouch.java

fix rune pouch

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/TransportLoader.java
runelite-client/src/main/resources/transports.json

Walker wouldn't open the trap door if it was closed but would go down if it was already open. This should fix it not opening the trap door.

Edgeville Dungeon Trap Door

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Walker.java

fix walker

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

Fixed Packet API for Rev 210

---

runelite-mixins/src/main/java/net/runelite/mixins/RSGraphicsObjectMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSSceneMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSGraphicsObject.java

This is a fix for commits e55eee197897aeb2cb701f6abbfcbcb31eb40244 5431414e5940bbe7044b1478ac4a690ef002b560

mixins: fix rl object

---

runelite-api/src/main/java/net/runelite/api/packets/ClientPacket.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java
runescape-api/src/main/java/net/runelite/rs/api/RSClientPacket.java
runescape-client/src/main/java/ClientPacket.java
runescape-client/src/main/java/WorldMapData_0.java

Added another widget packet

---

config/codestyle.xml

Intellij IDEA codestyle settings xml for contributors working on the project to follow
File -> Settings -> Code Style -> Scheme -> Import scheme

better codestyle

---

runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java

(cherry picked from commit 9d931f6a1921bd463914dee3ee3b57bb6f4700a8)

boolean support

---

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSWorldMap.java
runescape-api/src/main/java/net/runelite/rs/api/RSWorldMapArea.java

This is a fix for commit: 35ab5962834aff89c08672e7908c0d63ed56cea9

worldmap: fix deprecated api

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Walker.java

Added reachable check for draynor manor trees

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Walker.java

Transport delay fix applied to generic doors as they had the same issue

Added delay fix to generic doors

---

runelite-client/src/main/java/net/unethicalite/api/game/Worlds.java

Members world check switched to RuneLite API

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

Direct Packets Rev 212

---

runelite-api/src/main/java/net/runelite/api/World.java

This is an addition to commit: fedb6a8659de6131adf6723be6f7376303bd88b5

api: expose quest speedrunning

---

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/TransportLoader.java
runelite-client/src/main/resources/transports.json

Fixed Varrock Castle Manhole Transport

---

runelite-api/src/main/java/net/runelite/api/Item.java
runelite-client/src/main/java/net/unethicalite/api/magic/Magic.java

This should mark them as selected properly now

Fixed selecting items and spells

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

Fixed direct packet interactions for rev 213

---

runelite-client/src/main/java/net/runelite/client/events/ProfileChanged.java

Add this class so that RuneLite plugin-hub plugins with profile changed events keep working otherwise it throws java.lang.ClassCastException

client: add ProfileChanged event class

---

runelite-client/src/main/java/net/runelite/client/RuneLite.java

revert scale property

---

runelite-mixins/src/main/java/net/runelite/mixins/RSSceneMixin.java

this is an addition to commit: 58563df1078ad6d466552253097035304b1f9d5e

mixins: fire scene loading callbacks

---

runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java

Fixed array out of bounds exception caused by previous change

---

runescape-client/src/main/java/FloorDecoration.java

Fix GroundObjects incorrect x and y ObfuscatedGetter values

---

runelite-client/src/main/java/net/unethicalite/client/minimal/MinimalModule.java

Should fix minimal from crashing

Added provider for plugin hub to minimal module

---

runelite-client/src/main/java/net/runelite/client/plugins/unethicalite/ui/InteractionContainer.java
runelite-client/src/main/java/net/unethicalite/client/config/UnethicaliteConfig.java
runelite-client/src/main/java/net/unethicalite/client/managers/interaction/InteractionManager.java

Title. The option is off by default

Added option to send click packet when using packets or invokes

---

runelite-client/src/main/java/net/unethicalite/api/packets/MousePackets.java

Mouse packet no longer sends middle mouse button

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/TransportLoader.java
runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java
runescape-client/src/main/java/BoundaryObject.java
runescape-client/src/main/java/Buffer.java
runescape-client/src/main/java/Client.java
runescape-client/src/main/java/PacketWriter.java
runescape-client/src/main/java/class60.java

- Direct Packets: Updated API for direct packets, fixed wrong labeled methods in Buffer.class
- Boundary Object's X Value: Fixed wrong deobfuscation of x value

Rev 215.2 Direct Packets, Boundary Object's x value

---

runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

Fix widget on widget packet

---

runescape-client/src/main/java/com/jagex/oldscape/pub/OAuthApi.java

rev-216: add setClient(int var1)

---

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
runescape-api/src/main/java/net/runelite/rs/api/RSInterfaceParent.java
runescape-api/src/main/java/net/runelite/rs/api/RSNodeHashTable.java

This is an addition to commits: 7ef98e135986b6226e30989fc6dd441762076a2c 1e848e8fd2cec979ecb4d0e03af547d4adbd4cf8

mixins: rl interface open/close

---

runelite-client/src/main/java/net/unethicalite/api/game/Worlds.java
runelite-client/src/main/java/net/unethicalite/api/items/Bank.java
runelite-client/src/main/java/net/unethicalite/api/items/Trade.java

-fix incomplete "Offer/Deposit/Withdraw-X" sequence in Trade.offer(), Bank.deposit(), Bank.withdraw()
-change interact to "Offer-All" when >= quantity to offer instead of just > quantity in Trade.offer()

fix bank/trade withdraw-x

---

runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSActor.java
runescape-api/src/main/java/net/runelite/rs/api/RSIterableNodeHashTable.java

This is an addition to commit: 4037e4986b69945193910e5a1bca934eaa8fb5f7

mixins: ActorSpotAnim

---

runelite-api/src/main/java/net/runelite/api/Model.java
runelite-api/src/main/java/net/runelite/api/Renderable.java
runelite-mixins/src/main/java/net/runelite/mixins/ClickboxMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSDynamicObjectMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSModelDataMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSModelMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSActor.java
runescape-api/src/main/java/net/runelite/rs/api/RSDynamicObject.java
runescape-api/src/main/java/net/runelite/rs/api/RSModel.java

Model cleanup

---

runelite-client/src/main/resources/transports.json

Added in the underground pass transport locations, letting us walk around the area.

added Underground Pass transports

---

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/gpu/OpenCLManager.java
runelite-client/src/main/java/net/runelite/client/plugins/gpu/SceneUploader.java
runelite-client/src/main/resources/net/runelite/client/plugins/gpu/priority_render.cl
runelite-client/src/main/resources/net/runelite/client/plugins/gpu/priority_render.glsl
runelite-client/src/main/resources/net/runelite/client/plugins/gpu/vert.glsl

This reverts a part of commit: fdc93129e6188678dcda99ad4cd8c574e4c08fae

Revert "gpu: add extended scene"

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

Direct Packets for Rev 217

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Walker.java
runelite-client/src/main/java/net/unethicalite/client/config/UnethicaliteConfig.java

Added a section at the top of the main config to set the minimum and maximum step distance, rather than having the values hardcoded for everyone.
Edit: Forgot to mention that the default values are the same as it is now, so this shouldn't affect current scripts

Customisable Walker Steps

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Pathfinder.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/TeleportLoader.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/model/MovementConstants.java
runelite-client/src/main/java/net/unethicalite/client/config/UnethicaliteConfig.java
runelite-client/src/main/java/net/unethicalite/client/managers/RegionManager.java

Add equipment teleports method

---

runelite-client/src/main/java/net/runelite/client/plugins/unethicaldevtools/RegionOverlay.java

- remove duplicate menu code
+ made generateMenu method
+ add menu option to set start tile
+ add menu option to clear path
+ calculate path will now use start tile if present

update path debugger overlay

---

runelite-client/src/main/java/net/unethicalite/api/game/House.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/TransportLoader.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/model/MovementConstants.java

Hose.getOutsideLocation would reach out of bounds if player did not have a house

Fix walker house location idx error

---

runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java

This is an addition to commit: 7cbc8e51a5b88ab2616d748d5c5ba8f73189fe66

mixins: fix Actor getAnimation

---

runelite-mixins/src/main/java/net/runelite/mixins/RSJagexLauncherMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
runescape-client/src/main/java/Client.java
runescape-client/src/main/java/Login.java
runescape-client/src/main/java/LoginScreenAnimation.java
runescape-client/src/main/java/MusicPatchNode2.java
runescape-client/src/main/java/class155.java
runescape-client/src/main/java/class191.java
runescape-client/src/main/java/class223.java
runescape-client/src/main/java/class367.java
runescape-client/src/main/java/class429.java
runescape-client/src/main/java/class467.java

This is an addition to commit: babed9100982f3cd9c1a1a2d330646bea3038caf

rl-client: add --insecure-write-credentials

---

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
runelite-mixins/src/main/java/net/unethicalite/mixins/HClientMixin.java

This is an addition to commit: 22c85678b1f93231e5f18aa436ba5b0468a441fc

mixins: fix StatChanged event

---

runelite-client/src/main/java/net/unethicalite/client/minimal/MinimalClient.java
runelite-client/src/main/java/net/unethicalite/client/minimal/MinimalModule.java

This is an addition to commit: 8fef4437c8a3b6e14d2f8c297da9d9de6c322dea

minimal: add --insecure-write-credentials

---

runelite-mixins/src/main/java/net/runelite/mixins/RSNPCMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java
runelite-mixins/src/main/java/net/unethicalite/mixins/HActorMixin.java
runelite-mixins/src/main/java/net/unethicalite/mixins/HTileItemMixin.java

Change actor convexHull orientation to currentOrientation

mixins: actor getConvexHull current orientation

---

runelite-client/src/main/java/net/runelite/client/RuneLite.java
runelite-client/src/main/java/net/unethicalite/client/minimal/MinimalClient.java

Previously it copied cache to .openosrs/jagexcache/jagexcache/ instead of .openosrs/jagexcache/

fix cache path

---

runelite-client/src/main/java/net/unethicalite/api/script/paint/Paint.java
runelite-client/src/main/java/net/unethicalite/client/minimal/ui/MinimalToolbar.java

This will fix mouse debug and looped plugin

Fix minimal

---

runelite-client/src/main/java/net/unethicalite/api/items/Bank.java
runelite-client/src/main/java/net/unethicalite/api/items/Trade.java

copied getFreeSlots from Inventory into Bank.Inventory
added getTheirFreeSlots method to Trade as a way to get the the number of free slots for the other trading player

Bank.Inventory && Trade updates

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java
runelite-client/src/main/java/net/unethicalite/client/managers/interaction/InteractionManager.java

Fixed direct packets for rev 218

---

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClient.java

This is a fix for commit: 621cf2106a44a22968202a34fb79597051fe9480

mixins: fix AmbientSoundEffectCreated event

---

build.gradle.kts
runelite-mixins/src/main/java/net/runelite/mixins/RSJagexLauncherMixin.java

This requires [https://github.com/jbx5/devious-injector/pull/3](https://github.com/jbx5/devious-injector/pull/3)

RSJagexLauncherMixin: use injector for inlined credentials

---

deobfuscator/src/main/java/net/runelite/deob/deobfuscators/transformers/BadEnumConstructorTransformer.java
deobfuscator/src/main/java/net/runelite/deob/updater/UpdateMappings.java

Fix the wrongly de-obfuscated enum constructor where a final int field is not initialized

deob: (UpdateMappings) add BadEnumConstructorTransformer

---

deobfuscator/src/main/java/net/runelite/deob/deobfuscators/transformers/JSONSyntheticTransformer.java
deobfuscator/src/main/java/net/runelite/deob/updater/UpdateMappings.java

This is used to fix the org/json files

deob: (UpdateMappings) add JSONSyntheticTransformer

---

deobfuscator/src/main/java/net/runelite/deob/deobfuscators/transformers/ClassToPackageTransformer.java

Make ClassToPackageTransformer more reliably in case new classes get added

deob: (UpdateMappings) ClassToPackageTransformer update

---

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java

This prevents widget.getChild from throwing IndexOutOfBoundsException

Fix widget getchild

---

deobfuscator/src/main/java/net/runelite/deob/deobfuscators/mapping/MissingMappingChecker.java
deobfuscator/src/main/java/net/runelite/deob/updater/UpdateMappings.java

`2023-12-25 13:35:08 CET [main] INFO  n.r.d.d.m.MissingMappingChecker - Mapped missing class: ClassFile{name=SpriteBufferProperties} to: ClassFile{name=class541}
2023-12-25 13:35:16 CET [main] INFO  n.r.d.d.m.MissingMappingChecker - Mapped missing class: ClassFile{name=FillMode} to: ClassFile{name=class538}
2023-12-25 13:35:18 CET [main] INFO  n.r.d.d.m.MissingMappingChecker - Mapped missing class: ClassFile{name=SpriteBufferUtils} to: ClassFile{name=class458}
2023-12-25 13:35:23 CET [main] INFO  n.r.d.d.m.MissingMappingChecker - Mapped missing field: Lcom/jagex/oldscape/pub/RefreshAccessTokenRequester; Client.refreshAccessTokenRequester to: Lcom/jagex/oldscape/pub/RefreshAccessTokenRequester; client.field535
2023-12-25 13:35:24 CET [main] INFO  n.r.d.d.m.MissingMappingChecker - Mapped …

deob: (UpdateMapping) add MissingMappingChecker

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Pathfinder.java

Revert "remove gc call"

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

Fix direct packets for rev 219

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java

Thanks donkey9264 for pointing it out

Fix error in direct packets

---

runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java
runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
runelite-client/src/main/java/net/runelite/client/ui/ContainableFrame.java
runelite-client/src/main/java/net/runelite/client/ui/components/ToggleButton.java
runelite-client/src/main/java/net/runelite/client/util/ImageCapture.java
runelite-client/src/main/resources/net/runelite/client/ui/laf/RuneLiteLAF.properties

rl upstream branch where i will be pushing rl updates to

rl upstream

---

runelite-mixins/src/main/java/net/devious/mixins/DRSCachedDeviceIdMixin.java

f20d2b6c2e204d978f8a74a507c1a36300cd2540

mixins: use/fix cached device id for now

---

runelite-mixins/src/main/java/net/devious/mixins/DRSCachedDeviceIdMixin.java

Use `--cached-random-dat --cached-uuid` client arguments

mixins: DRSCachedDeviceIdMixin remove dialog

---

runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java

fixed widdgetOnObject packet

---

runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

had IME here too instead of ME

fixed widgetOnWidget

---

runescape-client/src/main/java/ObjectComposition.java

rs-client: (ObjectComposition) fix incorrect values

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/IgnoredDoorLoader.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Pathfinder.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/model/IgnoredDoor.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/model/requirement/ItemRequirement.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/model/requirement/Reduction.java
runelite-client/src/main/resources/ignoredDoors.json

This will allow ignoring doors, such as al-kharid gate with no coins

Add ignorable doors to pathfinder

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Pathfinder.java

grabs nearest walkable tile now to speed up walker

Fix pathfinder walking to blocked tiles

---

runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/IgnoredDoorLoader.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/Pathfinder.java
runelite-client/src/main/java/net/unethicalite/api/movement/pathfinder/model/IgnoredDoor.java
runelite-client/src/main/java/net/unethicalite/client/managers/RegionManager.java

Changed ignored doors to load with transports and used a map for better lookups during pathfinding.

Correct ignored doors to be load once

---

runelite-client/src/main/java/net/unethicalite/api/widgets/Dialog.java

Returns the question/title of an options dialog window.

dialog: add getQuestion() method for options dialogs

---

runelite-client/src/main/java/net/unethicalite/api/magic/Magic.java

a5ba5ca4d23cdadd717f1bfcb638210da6f3e34e

magic: fix widget spell action, name

---

runelite-client/src/main/java/net/runelite/client/eventbus/EventBus.java

Allow subscribing Runnables to the EventBus for dynamic programming shenanigans. This could be more elegant, but it is done in such a way that it does not break any existing code.
Also gets rid of some unneccessary "private final" uses, @Value applies those automatically

EventBus Runnable Support

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-api/src/main/java/net/runelite/api/Preferences.java
runelite-mixins/src/main/java/net/runelite/mixins/RSIntProjectionMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSProjectionMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSSceneMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSTilesProjectionMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClientPreferences.java
runescape-api/src/main/java/net/runelite/rs/api/RSIntProjection.java
runescape-api/src/main/java/net/runelite/rs/api/RSScene.java
runescape-client/src/main/java/ClientPreferences.java
runescape-client/src/main/java/IntProjection.java
runescape-client/src/main/java/Language.java
runescape-client/src/main/java/ReflectionCheck.java
runescape-client/src/main/java/class59.java
runescape-client/src/main/java/class92.java

-tile underlay & overlay hooks unfinished
f3403b75e16f0654a30260a79139fac7a9a753bb

mixins: (Scene) fix draw

---

runelite-api/src/main/java/net/runelite/api/Actor.java
runelite-api/src/main/java/net/runelite/api/Client.java
runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClient.java

This comes in handy sometimes and it makes more sense to put it here than in plugins.

Add getLastInteracting() method to Actor.java

---

runelite-client/src/main/java/net/unethicalite/api/packets/GroundItemPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/MovementPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/NPCPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/ObjectPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/PlayerPackets.java
runelite-client/src/main/java/net/unethicalite/api/packets/WidgetPackets.java

untested, lmk if anything is broken

packet fix rev 223
